"use client";
import {useEffect,useRef,useState} from 'react';
import {Search,X,LoaderCircle,MapPin} from 'lucide-react';
export type Place={label:string;detail:string;point:[number,number];kind:string};
const cache=new Map<string,Place[]>();
export function PlaceSearch({onChoose,disabled}:{onChoose:(p:Place)=>void;disabled:boolean}){
 const [query,setQuery]=useState(''),[results,setResults]=useState<Place[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[open,setOpen]=useState(false);
 const request=useRef<AbortController|null>(null),last=useRef(0),root=useRef<HTMLDivElement>(null),endpoint=useRef('https://photon.komoot.io/api/');
 useEffect(()=>{fetch((import.meta.env.BASE_URL||'/')+'search-config.json').then(r=>r.json()).then(c=>{if(c.endpoint?.startsWith('https://'))endpoint.current=c.endpoint;}).catch(()=>{});return()=>request.current?.abort();},[]);
 async function search(e:React.FormEvent){e.preventDefault();const q=query.trim();if(q.length<2){setMessage('Enter an address, city, ZIP code, neighborhood, or landmark.');setOpen(true);return;}if(busy||disabled)return;
  setOpen(true);setMessage('');if(cache.has(q.toLowerCase())){const cached=cache.get(q.toLowerCase())!;setResults(cached);if(!cached.length)setMessage('No Valley results found. Try adding the city or a nearby landmark.');return;}
  if(Date.now()-last.current<1500){setMessage('Please wait a moment before searching again.');return;}
  last.current=Date.now();request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setResults([]);const timer=setTimeout(()=>controller.abort(),15000);
  try{const url=new URL(endpoint.current);url.search=new URLSearchParams({q:/^\d{5}$/.test(q)?`${q} Arizona`:q,lat:'33.45',lon:'-112.07',bbox:'-113.5,32.45,-111.0,34.4',limit:'7',lang:'en'}).toString();const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error('Search is temporarily unavailable. Try again shortly, or select an area on the map.');const data=await r.json();if(data.error)throw Error('The search service could not process that query.');
   const places:Place[]=(data.features||[]).filter((f:any)=>f.geometry?.type==='Point'&&f.geometry.coordinates.length>=2&&f.geometry.coordinates.every(Number.isFinite)).map((f:any)=>{const p=f.properties||{};return {label:p.name||[p.housenumber,p.street].filter(Boolean).join(' ')||p.postcode||'Map location',detail:[p.housenumber&&p.name?[p.housenumber,p.street].filter(Boolean).join(' '):null,p.city||p.district,p.state,p.postcode].filter(Boolean).join(', '),point:f.geometry.coordinates,kind:p.type||'place'};});
   cache.set(q.toLowerCase(),places);if(cache.size>40)cache.delete(cache.keys().next().value!);setResults(places);if(!places.length)setMessage('No Valley results found. Try adding the city or a nearby landmark.');
  }catch(e:any){if(request.current===controller)setMessage(e.name==='AbortError'?'Search timed out. Please try again.':e.message||'Search could not connect. You can still use the map.');}finally{clearTimeout(timer);if(request.current===controller)setBusy(false);}
 }
 return <div className="place-search" ref={root} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);}}><form role="search" onSubmit={search}><Search size={18}/><input aria-label="Search an address or place" placeholder="Address, city, ZIP, or landmark" value={query} onChange={e=>setQuery(e.target.value)} maxLength={180}/><button type="submit" disabled={busy||disabled} aria-label="Search places">{busy?<LoaderCircle className="spin" size={18}/>:<span>Search</span>}</button></form>{open&&<section className="search-results" aria-label="Search results"><div className="results-heading"><strong>{busy?'Searching the Valley…':'Search results'}</strong><button onClick={()=>setOpen(false)} aria-label="Close search results"><X size={18}/></button></div>{message&&<p role="status">{message}</p>}<ul>{results.map((p,i)=><li key={i}><button onClick={()=>{setQuery(p.label);setOpen(false);onChoose(p);}}><MapPin size={17}/><span><strong>{p.label}</strong><small>{p.detail||p.kind}</small></span></button></li>)}</ul><p className="search-credit">Search: <a href="https://photon.komoot.io" target="_blank" rel="noreferrer">Photon</a> / <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>. Only submitted searches are sent to the provider. Locations may be approximate.</p></section>}</div>;
}
